#pragma once
#include <math.h>
#include <cstdint>
#include <vector>
#include <string>
#include <array>
#include <d3d11.h>
#include <Windows.h>
#include <winternl.h>
#include <dxgi1_2.h>
#include <wrl/client.h>
#include <chrono>
#include <thread>
#include <iostream>
#include <strsafe.h>